// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: _bootstrap.sql

package DAL

import (
	"context"
)

const healthcheck = `-- name: Healthcheck :one
SELECT 1::int
`

func (q *Queries) Healthcheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, healthcheck)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
