// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package DAL

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const upsertDocumentFetch = `-- name: UpsertDocumentFetch :one
INSERT INTO documents (url, fetched_at, status_code, content_type, content_hash, raw_content)
VALUES ($1, now(), $2, $3, $4, $5) ON CONFLICT (url) DO
UPDATE
    SET fetched_at = now(),
    status_code = EXCLUDED.status_code,
    content_type = EXCLUDED.content_type,
    content_hash = EXCLUDED.content_hash,
    raw_content = EXCLUDED.raw_content
    RETURNING id, url, fetched_at, status_code, content_type, content_hash
`

type UpsertDocumentFetchParams struct {
	Url         string
	StatusCode  int32
	ContentType string
	ContentHash sql.NullString
	RawContent  []byte
}

type UpsertDocumentFetchRow struct {
	ID          uuid.UUID
	Url         string
	FetchedAt   time.Time
	StatusCode  int32
	ContentType string
	ContentHash sql.NullString
}

func (q *Queries) UpsertDocumentFetch(ctx context.Context, arg UpsertDocumentFetchParams) (UpsertDocumentFetchRow, error) {
	row := q.db.QueryRowContext(ctx, upsertDocumentFetch,
		arg.Url,
		arg.StatusCode,
		arg.ContentType,
		arg.ContentHash,
		arg.RawContent,
	)
	var i UpsertDocumentFetchRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.FetchedAt,
		&i.StatusCode,
		&i.ContentType,
		&i.ContentHash,
	)
	return i, err
}
