// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: EnqueueURL.sql

package DAL

import (
	"context"
)

const enqueueURL = `-- name: EnqueueURL :exec
INSERT INTO crawl_queue (url, status, attempts, next_run_at, last_error) 
VALUES ($1, 'pending', 0, now(), null)
    ON CONFLICT (url) DO UPDATE
        SET status = CASE
                        WHEN crawl_queue.status IN ('crawled') THEN crawl_queue.status
                        ELSE 'pending'
                     END,
            next_run_at = LEAST(crawl_queue.next_run_at, now()),
            updated_at = now()
`

func (q *Queries) EnqueueURL(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, enqueueURL, url)
	return err
}
