// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: EnsureQueueURL.sql

package DAL

import (
	"context"
)

const ensureQueueURL = `-- name: EnsureQueueURL :exec
INSERT INTO crawl_queue (url, status, attempts, last_error, next_run_at)
VALUES ($1, 'pending', 0, NULL, now())
    ON CONFLICT (url) DO NOTHING
`

func (q *Queries) EnsureQueueURL(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, ensureQueueURL, url)
	return err
}
