// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetDocumentHashByURL.sql

package DAL

import (
	"context"
	"database/sql"
)

const getDocumentHashByURL = `-- name: GetDocumentHashByURL :one
SELECT content_hash
FROM documents
WHERE url = $1
`

func (q *Queries) GetDocumentHashByURL(ctx context.Context, url string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getDocumentHashByURL, url)
	var content_hash sql.NullString
	err := row.Scan(&content_hash)
	return content_hash, err
}
