// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: MarkQueueCrawled.sql

package DAL

import (
	"context"
)

const markQueueCrawled = `-- name: MarkQueueCrawled :exec
UPDATE crawl_queue
SET status      = 'crawled',
    last_error  = NULL,
    locked_at  = NULL,
    updated_at  = now()
WHERE url = $1
`

func (q *Queries) MarkQueueCrawled(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, markQueueCrawled, url)
	return err
}
