// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: MarkQueueFailed.sql

package DAL

import (
	"context"
	"database/sql"
)

const markQueueFailed = `-- name: MarkQueueFailed :exec
UPDATE crawl_queue
SET status      = 'failed',
    attempts    = attempts + 1,
    last_error  = $2,
    next_run_at = now() + ($3::interval),
    updated_at  = now()
WHERE url = $1
`

type MarkQueueFailedParams struct {
	Url       string
	LastError sql.NullString
	Column3   int64
}

func (q *Queries) MarkQueueFailed(ctx context.Context, arg MarkQueueFailedParams) error {
	_, err := q.db.ExecContext(ctx, markQueueFailed, arg.Url, arg.LastError, arg.Column3)
	return err
}
