// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package DAL

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CrawlQueue struct {
	ID        int64
	Url       string
	Status    string
	Attempts  int32
	LastError sql.NullString
	NextRunAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Document struct {
	ID          uuid.UUID
	Url         string
	FetchedAt   sql.NullTime
	StatusCode  sql.NullInt32
	ContentType sql.NullString
	ContentHash sql.NullString
	RawContent  sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DocumentSearch struct {
	DocumentID   uuid.UUID
	SearchVector interface{}
}

type DocumentText struct {
	DocumentID  uuid.UUID
	Title       sql.NullString
	Body        sql.NullString
	Language    sql.NullString
	CleanedText sql.NullString
	ExtractedAt sql.NullTime
	UpdatedAt   time.Time
}
