// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ReleaseStaleProcessing.sql

package DAL

import (
	"context"
	"database/sql"
)

const releaseStaleProcessing = `-- name: ReleaseStaleProcessing :exec
UPDATE crawl_queue
SET status     = 'pending',
    locked_at  = NULL,
    updated_at = now()
WHERE status = 'processing'
  AND locked_at IS NOT NULL
  AND locked_at < (now() - ($1)::interval)
`

func (q *Queries) ReleaseStaleProcessing(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, releaseStaleProcessing, dollar_1)
	return err
}
