// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: TouchDocumentFetchedAt.sql

package DAL

import (
	"context"
)

const touchDocumentFetchedAt = `-- name: TouchDocumentFetchedAt :exec
UPDATE documents
SET fetched_at = now(),
    status_code = $2,
    content_type = $3
WHERE url = $1
`

type TouchDocumentFetchedAtParams struct {
	Url         string
	StatusCode  int32
	ContentType string
}

func (q *Queries) TouchDocumentFetchedAt(ctx context.Context, arg TouchDocumentFetchedAtParams) error {
	_, err := q.db.ExecContext(ctx, touchDocumentFetchedAt, arg.Url, arg.StatusCode, arg.ContentType)
	return err
}
